### ISSUE TITLE
It would be good adding hoverable on quotes card

### ISSUE THREAD

**Issue by akrindev** [nyancodeid/quotes#30]
to make it looks live, I add hoverable element on quotes card.

it will look like this

https://user-images.githubusercontent.com/33445459/135796638-a24bc74e-e9b0-4634-a87d-51e88a98cec2.mp4

uhh I'm staring at it ✨

**Comment by nyancodeid** [comment]
That's what we looking for, a hover effect. Thank you 🤩

**Comment by nyancodeid** [comment]
We reopen this issue, because it's come with another issue. If you can see we have little corner here, i think it because we move `rounded-3xl shadow-lg` class to the child element. I tested out move all hover animation to the parent element. And it's works. So what do you think about this @akrindev ? thanks.

## Lil corner
![image](https://user-images.githubusercontent.com/24630806/135799683-95c66ecc-7442-4db6-ba02-f32220409dc3.png)

## Side by side
![image](https://user-images.githubusercontent.com/24630806/135799977-340b6616-ff4a-44fc-a69c-eaa1858018b9.png)

**Comment by akrindev** [comment]
I get it, there's another issue that whenever the cursor hover the element it trigger the parent element, that look like the animation is cutting while the cursor is moving out. look carefully

https://user-images.githubusercontent.com/33445459/135802947-c5739b08-bce1-40e8-be15-57ed90f12c1c.mp4


moving the hover to its parent is solving the issue, look so clear and smooth

https://user-images.githubusercontent.com/33445459/135803060-487a19b0-eb81-4b35-aa91-22ecc774d2b4.mp4

**Comment by nyancodeid** [comment]
Cool, i am gonna see your pull-request

**Comment by nyancodeid** [comment]
Perfect, thanks @akrindev
